version: '2'
services:
  spark-master:
    image: stacktraceyo/spork-master
    container_name: spark-master
    ports:
      - "8080:8080" # UI port
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: stacktraceyo/spork-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # UI port
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"